// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBG.Visitor.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NBG.Visitor.Storage.Migrations
{
    [DbContext(typeof(VisitContext))]
    [Migration("20211026134916_CompanyFix")]
    partial class CompanyFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Company", b =>
                {
                    b.Property<string>("CompanyLabel")
                        .HasColumnType("text")
                        .HasColumnName("company_label");

                    b.HasKey("CompanyLabel");

                    b.HasIndex("CompanyLabel")
                        .IsUnique();

                    b.ToTable("company");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.ContactPerson", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("contact_person");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Visit", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VisitEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visit_end");

                    b.Property<DateTime?>("VisitStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visit_start");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.Property<string>("company_label")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonName");

                    b.HasIndex("VisitorId");

                    b.HasIndex("company_label");

                    b.ToTable("visit");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Visitor", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("visitor");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Visit", b =>
                {
                    b.HasOne("NBG.Visitor.Storage.Models.ContactPerson", "ContactPerson")
                        .WithMany("Visits")
                        .HasForeignKey("ContactPersonName");

                    b.HasOne("NBG.Visitor.Storage.Models.Visitor", "Visitor")
                        .WithMany("Visits")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBG.Visitor.Storage.Models.Company", "Company")
                        .WithMany("Visits")
                        .HasForeignKey("company_label");

                    b.Navigation("Company");

                    b.Navigation("ContactPerson");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Company", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.ContactPerson", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("NBG.Visitor.Storage.Models.Visitor", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
